export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const SAVE_USER_DATA = "SAVE_USER_DATA";
export const CLEAR_USER_DATA = "CLEAR_USER_DATA";

export const SET_RECEIVED_MESSAGES_FOR_ACCOUNT =
  "SET_RECEIVED_MESSAGES_FOR_ACCOUNT";
export const SET_RECEIVED_MESSAGES_AS_READ = "SET_RECEIVED_MESSAGES_AS_READ";
export const CLEAR_RECEIVED_MESSAGES_FOR_ACCOUNT =
  "CLEAR_RECEIVED_MESSAGES_FOR_ACCOUNT";

export const SET_SENT_MESSAGES_FOR_ACCOUNT = "SET_SENT_MESSAGES_FOR_ACCOUNT";
export const SET_SENT_MESSAGE_AS_READ = "SET_SENT_MESSAGE_AS_READ";
export const CLEAR_SENT_MESSAGES_FOR_ACCOUNT =
  "CLEAR_SENT_MESSAGES_FOR_ACCOUNT";

export const SET_TEACHERS_LIST = "SET_TEACHERS_LIST";
export const CLEAR_TEACHERS_LIST = "CLEAR_TEACHERS_LIST";
