# Generated by Django 3.1.2 on 2020-12-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20201109_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='subject_id',
            new_name='subject',
        ),
    ]
