# Generated by Django 3.1.2 on 2020-12-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20201216_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='attachment',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
