# Generated by Django 3.1.3 on 2021-01-13 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20201230_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='firstRetakeValue',
            field=models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='grade',
            name='secondRetakeValue',
            field=models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)]),
        ),
    ]
